<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use function foo\func;

class Post extends Model
{
    //
    protected $fillable = ['title','content','user_id','status'];//可以使用注入字段
    protected $datas = ['delete_time'];
    public function user(){
        return $this->belongsTo('App\user','user_id','id');
    }
    //一对多关联
    public function comments(){
        return $this->hasMany('App\Comment')->orderByDesc('created_at');
    }
    //点赞一对多关联
    public function zans(){
        return $this->hasMany('\App\Zan');
    }
    //点赞一对一关联
    public function zan($user_id){
        return $this->hasOne(\App\Zan::class)->where('user_id',$user_id);
    }

    //使用scope过滤属于当前用户的文章
    public function scopeAuthorBy(Builder $query,$user_id){
        return $query->where('user_id',$user_id);
    }
    //使用一对多关联post
    public function postTopics(){
        return $this->hasMany(\App\PostTopic::class ,'post_id');
    }
    //不属于当前专题的文章
    public function scopeTopicNot(Builder $query ,$topic_id){
        return $query->doesntHave('postTopics','and',function ($q) use($topic_id) {
            $q->where('topic_id',$topic_id);
        });
    }
    //全局
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope('avaiable',function (Builder $builder){
           $builder->whereIn('status',[0,1])->where('delete_time',0);
        });
    }
}

